#!/usr/bin/env python

import rospy
from counter.msg import Count

class Accumulator(object):
    """ Accumulate the total of messages in subscribed nodes  """
    def __init__(self):
        self.count = 0
        rospy.Subscriber("count", Count, self.callback)

    def callback(self, data):
        self.count += data.count
        oospy.loginfo(rospy.get_name() + " recieved from " + data.mode + " count %d", self.count)

def main():
    rospy.init_node("accumulate")
    Accumulator()
    rospy.spin()


if __name__ == "__main__":
   try:
      main()
   except rospy.ROSInterruptException:
      pass
