#!/usr/bin/env python
"""
Publishes a count that is constant, once per second

PUBLISHERS:
   count (Count) ~ Publishes the count
"""

import rospy
from counter.msg import Count

def main():
   rospy.init_node('count_up')
   pub = rospy.Publisher("count", Count, queue_size = 10)
   rate = rospy.Rate(1)

   while not rospy.is_shutdown():
      pub.publish(Count(mode=rospy.get_name(), count = 1))
      rate.sleep()

if __name__ == "__main__":
   try:
      main()
   except rospy.ROSInterruptException:
      pass

         
